GET http://localhost:8080/user/list?name=test

###

POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "username":"hhc",
  "name":"贺泓超",
  "password": "123456"
}

###
GET http://localhost:8080/user/info/355950515865128960

###