GET http://localhost:8080/user/list?name=test

###

POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "username":"hhc",
  "name":"贺泓超",
  "password": "123456"
}

###

GET http://localhost:8080/user/info/355950515865128960

###
POST http://localhost:8080/user/updateInfo
Content-Type: application/json

{
  "id": "355950714255708160",
  "name": "测试3第五遍修改后",
  "selfIntro": "我是谁呢",
  "age": 20,
  "gender": "male",
  "circles": "摇滚，游泳，摄影",
  "managedCircles": "摇滚",
  "tags": "游戏达人,摇滚音乐人",
  "status": false
}

###

GET http://localhost:8080/user/getUserInfoByName/测

###

GET http://localhost:8080/user/getUserListByTags/摇滚

###